### PR TITLE
Add OpenSfM to basic installation

### PR DESCRIPTION
**Pull request by Valdimus**
As ask by @zyioump I add OpenSfM to the ansible. @zyioump can you test it ?

### CODE REVIEW

**Review by TomEros — COMMENTED** [review]
Why not using git lfs for storing binary files ?

**Comment by Valdimus** [comment]
I can build the test data set Berlin from mapillary with the new version of OpenSfM (https://github.com/OpenPathView/OpenSfM/pull/3).
All seem to be ok, we can merge it.

**Review by zyioump — COMMENTED** [review]
Tested

**Review by zyioump — DISMISSED** [review]
Test approve

**Review by Benvii — DISMISSED** [review]
@zyioump had trouble testing it. @zyioump can you post here the exception we had testing this PR and how we tested it.

According to the docker file "Dockerfile.python3" (in OpenSfM repository), there is a python3 version we should test this version and if it works install it in the "opv" virtual env.

@zyioump or @Valdimus can you test the python3 version of OpenSfM ?

**Comment by Benvii** [comment]
@zyioump told me that he successfully run OpenSfM using Python3 today, he didn't managed to install it through Ansible but he is working on it.

Please post here your advances so that you can both work in sync remotely (without having me as intermediary ;) ).

**Comment by Valdimus** [comment]
Test with the lund data from OpenSfM, it works.

**Review by Benvii — APPROVED** [review]
Ok

**Pull request merged**
