### PR TITLE
Move form Spark to Celery

### PR DESCRIPTION
**Pull request by Valdimus**
Go back to celery. I redeploy and all works well.

### CODE REVIEW

**Comment by Benvii** [comment]
I will take a look at it tomorrow.

**Comment by Benvii** [comment]
I deployed the containers and try to start stitching a campaign but nothing happened : 
```
(opv) opv@opv_master:~/dev/OPV_214JJ_Test$ opv-celery-campaign 1 42
24 panorama to make: [{'id_malette': 42, 'id_lot': 1}, {'id_malette': 42, 'id_lot': 2}, {'id_malette': 42, 'id_lot': 3}, {'id_malette': 42, 'id_lot': 4}, {'id_malette': 42, 'id_lot': 5}, {'id_malette': 42, 'id_lot': 6}, {'id_malette': 42, 'id_lot': 7}, {'id_malette': 42, 'id_lot': 8}, {'id_malette': 42, 'id_lot': 9}, {'id_malette': 42, 'id_lot': 10}, {'id_malette': 42, 'id_lot': 11}, {'id_malette': 42, 'id_lot': 12}, {'id_malette': 42, 'id_lot': 13}, {'id_malette': 42, 'id_lot': 14}, {'id_malette': 42, 'id_lot': 15}, {'id_malette': 42, 'id_lot': 16}, {'id_malette': 42, 'id_lot': 17}, {'id_malette': 42, 'id_lot': 18}, {'id_malette': 42, 'id_lot': 19}, {'id_malette': 42, 'id_lot': 20}, {'id_malette': 42, 'id_lot': 21}, {'id_malette': 42, 'id_lot': 22}, {'id_malette': 42, 'id_lot': 23}, {'id_malette': 42, 'id_lot': 24}]
```

Where is flower ?
Anyway to debug it ?

**Comment by zyioump** [comment]
Error while installing redis, systemd can't run it, I can run it by hand.
```root@master1:~# apt install redis-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
redis-server is already the newest version (2:3.0.6-1ubuntu0.2).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Setting up redis-server (2:3.0.6-1ubuntu0.2) ...
Job for redis-server.service failed because the control process exited with error code. See "systemctl status redis-server.service" and "journalctl -xe" for details.
invoke-rc.d: initscript redis-server, action "start" failed.
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2018-12-08 13:52:10 UTC; 17ms ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 665 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=226/NAMESPACE)
  Process: 664 ExecStartPre=/bin/run-parts --verbose /etc/redis/redis-server.pre-up.d (code=exited, status=226/NAMESPACE)

Dec 08 13:52:10 master1 systemd[1]: Failed to start Advanced key-value store.
Dec 08 13:52:10 master1 systemd[1]: redis-server.service: Unit entered failed state.
Dec 08 13:52:10 master1 systemd[1]: redis-server.service: Failed with result 'exit-code'.
dpkg: error processing package redis-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 redis-server
E: Sub-process /usr/bin/dpkg returned an error code (1)```

**Review by zyioump — APPROVED** [review]
Tested in contaier

**Pull request merged**
